version: '3.9'
networks:
  testnet:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"

volumes:
  mysql5_7:
  nacos:
  sentinel:


services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Imoa8024
    networks:
      testnet:
        ipv4_address: "172.30.0.30"
    volumes:
      - mysql5_7:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  nacos:
    image: nacos/nacos-server:1.1.4
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - MYSQL_DATABASE_NUM=1
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=Imoa8024
    networks:
      testnet:
        ipv4_address: "172.30.0.31"
    volumes:
      - nacos:/home/nacos
    ports:
      - "8848:8848"
    depends_on:
      - mysql
    restart: always

  sentinel:
    image: bladex/sentinel-dashboard:latest
    container_name: sentinel
    networks:
      testnet:
        ipv4_address: "172.30.0.32"
    volumes:
      - sentinel:/tmp/sentinel
    ports:
      - "8858:8858"
    restart: always
