version: '3.9'
networks:
  testnet:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"

volumes:
  kafka1:
  kafka2:
  kafka3:

services:
  kafka1:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9082:9082"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9082
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://192.168.199.113:9082
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      testnet:
        ipv4_address: "172.30.0.21" 
    extra_hosts:
      - "zoo1:172.30.0.11"
      - "zoo2:172.30.0.12"
      - "zoo3:172.30.0.13"
    volumes:
      - kafka1:/kafka

  kafka2:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9083:9083"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9083
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9093,OUTSIDE://192.168.199.113:9083
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      testnet:
        ipv4_address: "172.30.0.22" 
    extra_hosts:
      - "zoo1:172.30.0.11"
      - "zoo2:172.30.0.12"
      - "zoo3:172.30.0.13"
    volumes:
      - kafka2:/kafka

  kafka3:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9084:9084"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9084
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9094,OUTSIDE://192.168.199.113:9084
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      testnet:
        ipv4_address: "172.30.0.23" 
    extra_hosts:
      - "zoo1:172.30.0.11"
      - "zoo2:172.30.0.12"
      - "zoo3:172.30.0.13"
    volumes:
      - kafka3:/kafka