version: '3.9'
networks:
  testnet:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"

volumes:
  zoo1_data:
  zoo2_data:
  zoo3_data:
  zoo1_datalog:
  zoo2_datalog:
  zoo3_datalog:

services:
  zoo1:
    image: zookeeper:3.4.13
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      testnet:
        ipv4_address: "172.30.0.11"
    volumes:
      - zoo1_data:/data
      - zoo1_datalog:/datalog
        
  zoo2:
    image: zookeeper:3.4.13
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      testnet:
        ipv4_address: "172.30.0.12"
    volumes:
      - zoo2_data:/data
      - zoo2_datalog:/datalog

  zoo3:
    image: zookeeper:3.4.13
    hostname: zoo3
    container_name: zoo3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      testnet:
        ipv4_address: "172.30.0.13"
    volumes:
      - zoo3_data:/data
      - zoo3_datalog:/datalog

